[workspace]
members = [
    "driver",
    "kernel",
    "libsupervisionary",
    "tests/type",
    "tests/type_former",
    "wasmi-bindings"
]

[profile.release]
lto           = true
opt-level     = 3
codegen-units = 1
