[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
description = "Builds the Supervisionary kernel"
command     = "cargo"
args        = ["build", "--release"]

[tasks.clean]
description = "Cleans all built kernel object files and executables."
command     = "cargo"
args        = ["clean"]

[tasks.test]
description = "Runs module-level unit tests for the kernel."
command     = "cargo"
args        = ["test"]

[tasks.clippy]
description   = "Runs the Clippy linter on the kernel source files."
install_crate = "clippy"
command       = "cargo"
args          = ["clippy"]

[tasks.format]
description   = "Formats the kernel source code."
install_crate = "rustfmt"
command       = "cargo"
args          = ["fmt"]

[tasks.document]
description   = "Generates rustdoc documentation from the kernel source code."
install_crate = "rustdoc"
command       = "cargo"
args          = ["doc", "--no-deps"]

[tasks.all]
description  = "Build, lint, format, and test the Supervisionary kernel"
dependencies = ["clean", "format", "build", "clippy", "test", "document"]
