[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
description = "Builds the Supervisionary system interface."
command     = "cargo"
args        = ["build", "--release"]

[tasks.clean]
description = "Cleans all built system interface object files."
command     = "cargo"
args        = ["clean"]

[tasks.test]
description = "Runs module-level unit tests for the Supervisionary system interface."
command     = "cargo"
args        = ["test"]

[tasks.clippy]
description   = "Runs the Clippy linter on the Supervisionary system interface."
install_crate = "clippy"
command       = "cargo"
args          = ["clippy"]

[tasks.format]
description   = "Formats the Supervisionary system interface source code."
install_crate = "rustfmt"
command       = "cargo"
args          = ["fmt"]

[tasks.document]
description   = "Generates rustdoc documentation from the Supervisionary system interface source code."
install_crate = "rustdoc"
command       = "cargo"
args          = ["doc", "--no-deps"]

[tasks.all]
description  = "Build, lint, format, and test the Supervisionary system interface."
dependencies = ["clean", "format", "build", "clippy", "test", "document"]
