[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
description = "Builds the Supervisionary type-former tests"
command     = "cargo"
args        = ["build", "--release", "--target=wasm32-unknown-unknown"]

[tasks.clean]
description = "Cleans all built type-former tests object files and executables."
command     = "cargo"
args        = ["clean"]

[tasks.test]
description = "Runs module-level unit tests for the type-former tests."
command     = "cargo"
args        = ["test"]

[tasks.clippy]
description   = "Runs the Clippy linter on the type-former tests source files."
install_crate = "clippy"
command       = "cargo"
args          = ["clippy"]

[tasks.format]
description   = "Formats the type-former tests source code."
install_crate = "rustfmt"
command       = "cargo"
args          = ["fmt"]

[tasks.document]
description   = "Generates rustdoc documentation from the type-former tests source code."
install_crate = "rustdoc"
command       = "cargo"
args          = ["doc", "--no-deps"]

[tasks.all]
description  = "Build, lint, format, and test the Supervisionary type-former tests"
dependencies = ["clean", "format", "build", "clippy", "test", "document"]
